# Generated by Django 2.2.2 on 2021-12-06 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.CharField(max_length=100, null=True)),
                ('time2', models.CharField(max_length=100, null=True)),
                ('time3', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cornellstu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('absences', models.IntegerField(null=True)),
                ('courseinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysystem.course')),
            ],
        ),
    ]
