# Generated by Django 2.2.2 on 2021-12-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornellstu',
            name='netid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
