# Generated by Django 2.2.2 on 2021-12-07 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0003_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anouncement',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
