# Generated by Django 2.2.2 on 2021-12-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0004_auto_20211207_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveyresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans1', models.BooleanField(default=False)),
                ('ans2', models.BooleanField(default=False)),
                ('ans3', models.BooleanField(default=False)),
                ('ans4', models.BooleanField(default=False)),
                ('ans5', models.BooleanField(default=False)),
                ('ans6', models.BooleanField(default=False)),
                ('ans7', models.BooleanField(default=False)),
                ('ans8', models.BooleanField(default=False)),
                ('ans9', models.BooleanField(default=False)),
                ('ans10', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Surveytable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null=True)),
                ('question1', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
