# Generated by Django 2.2.2 on 2021-12-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0005_surveyresult_surveytable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresult',
            name='ans10',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='ans4',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='ans5',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='ans6',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='ans7',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='ans8',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='ans9',
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='ans1',
            field=models.IntegerField(default=0),
        ),
    ]
